package person.sa.dataobject;

public class ItemStockDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbg.generated Fri Jun 14 21:57:29 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock
     *
     * @mbg.generated Fri Jun 14 21:57:29 CST 2019
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.item_id
     *
     * @mbg.generated Fri Jun 14 21:57:29 CST 2019
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     * @mbg.generated Fri Jun 14 21:57:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     * @mbg.generated Fri Jun 14 21:57:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock
     *
     * @return the value of stock.stock
     * @mbg.generated Fri Jun 14 21:57:29 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock
     *
     * @param stock the value for stock.stock
     * @mbg.generated Fri Jun 14 21:57:29 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.item_id
     *
     * @return the value of stock.item_id
     * @mbg.generated Fri Jun 14 21:57:29 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.item_id
     *
     * @param itemId the value for stock.item_id
     * @mbg.generated Fri Jun 14 21:57:29 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
}