package person.sa.dao;

import org.apache.ibatis.annotations.Param;
import person.sa.dataobject.ItemStockDO;

public interface ItemStockDOMapper {
    ItemStockDO selectByItemId(Integer id);

    int decreaseStock(@Param("itemId") Integer itemId,
                      @Param("amount") Integer amount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Fri Jun 14 21:57:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Fri Jun 14 21:57:29 CST 2019
     */
    int insert(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Fri Jun 14 21:57:29 CST 2019
     */
    int insertSelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Fri Jun 14 21:57:29 CST 2019
     */
    ItemStockDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Fri Jun 14 21:57:29 CST 2019
     */
    int updateByPrimaryKeySelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Fri Jun 14 21:57:29 CST 2019
     */
    int updateByPrimaryKey(ItemStockDO record);
}